name: Changelog CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: changelog-ci
        uses: saadmk11/changelog-ci@v1.1.2
        id: changelog-ci

      - name: Get Changelog Output
        run: |
            echo "${{ steps.changelog-ci.outputs.changelog }}"



        