name: 'version check'

on:
    pull_request: 
      branches: 
        - phaser-release

jobs:
    check:
      permissions:
        contents: write
      runs-on: 'ubuntu-22.04'
      steps:

        - uses: actions/checkout@v4
        - name: install dependencies (ubuntu only)
          run: |
            sudo apt-get update
            sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

        - name: setup node
          uses: actions/setup-node@v4
          with:
            node-version: lts/*
            cache: 'npm'
      
        - uses: actions/checkout@v2
        - name: Set output
          id: vars
          run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
        - name: Check output
          env:
            RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
          run: |
            echo $RELEASE_VERSION
            echo ${{ steps.vars.outputs.tag }}
            ls -l
            cat package.json
            npm run ver-check ${{ steps.vars.outputs.tag }}
  