name: 'version check'

on:
    pull_request: 
      branches: 
        - phaser-release

jobs:
    update-version:
      permissions:
        contents: write
      runs-on: 'ubuntu-22.04'
      steps:
        - name: setup node
          uses: actions/setup-node@v4
          with:
            node-version: lts/*
            cache: 'npm'
      
        - uses: actions/checkout@v2
        - name: Set output
          id: vars
          run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
        - name: Check output
          env:
            RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
          run: |
            echo $RELEASE_VERSION
            echo ${{ steps.vars.outputs.tag }}
            node ../../scripts/check-version.js ${{ steps.vars.outputs.tag }}
  